### ISSUE TITLE
How to use this in combination with coffeescript?

### ISSUE THREAD

**Issue by varblob** [pangratz/ember-cli-htmlbars-inline-precompile#17]
Back ticks escaping to pure js in ember-cli-coffeescript.  Any suggestions on how to get past this.

**Comment by pangratz** [comment]
Sorry, my Coffeescript skills are very limited so I don't really know if there is a way. I tried using [embedded JavaScript](http://coffeescript.org/#embedded) functionality but this doesn't work since the backtick is used for escaping ...

One possible way I could think of is defining the templates in an ES6 file and import them in your Coffeescript, but the advantage of seeing the template in the test is lost. Something like the following (untested):

``` js
// tests/templates.js
import hbs from 'htmlbars-inline-precompile';

export var testTemplate = hbs`
  {{#my-component}}
    hello
  {{/my-component}}
`;
```

``` coffeescript
// tests/unit/component/my-component.coffee
import { testTemplate } from '../../../templates';

test "it works", (assert) ->
  @render testTemplate

  assert.equals @$().html().text().trim(), "hello"
```

**Comment by varblob** [comment]
I think your idea should work but as you stated it makes the tests considerably less readable.  It's too bad there isn't a way to escape backticks so I could do something like `hbs\`{{#my-component}}hello{{/my-component}}\``.  I'm gonna see if maybe coffeescript has something to say about escaping backticks.

**Comment by pangratz** [comment]
I have another idea: `hbs('template string')` will be precompiled by `ember-cli-htmlbars-inline-precompile` as well (not just tagged template strings, like currently). This allows you to write tests in Coffeescript like this:

``` coffeescript
`import hbs from 'ember-cli-htmlbars-inline-precompile';`

test "it works", (assert) ->
  @render '
    {{#my-component}}
      hello
    {{/my-component}}
  '

  assert.equals @$().html().text().trim(), "hello"
```

**Comment by pangratz** [comment]
I released `0.2.0` which adds support for passing a single string to the `hbs()` function. See [tests/unit/components/coffeescript-support-test.coffee](http://git.io/vqF8i) and [tests/unit/views/precompile-test.js](http://git.io/vqF8y) on how this is used.

Thanks for opening the issue and giving me the idea to enhance this addon! :beers: 

I am going to close this issue. Feel free to comment if you have any issues. Cheers!

**Comment by varblob** [comment]
Works a charm, if you're ever in NY I owe you a beer!

**Comment by pangratz** [comment]
Great, glad it works. Happy testing!
