### ISSUE TITLE
doesn't work with babel-core 5.7

### ISSUE THREAD

**Issue by piotrpalek** [pangratz/ember-cli-htmlbars-inline-precompile#18]
Hey, I just started using this and it's great for integration testing components. 
Everything worked fine, after I started using it, but then I removed/reinstalled `node_modules` and `bower_components` and I got a build error which ended in `somefile: TODO` which I suspect is this line in babel-core: https://github.com/babel/babel/blob/master/packages/babel/src/traversal/path/replacement.js#L67.

When I replaced the `babel-core` dependency in `broccoli-babel-transpiler` to `5.6.19` it worked again (I replaced it by removing the directory and replacing it with a local copy of that `babel-core` version).
Before replacing it the `babel-core` version was `5.7.0` which didn't work.

**Comment by pangratz** [comment]
Thanks for reporting! It looks like the line you suspected is the problem. I will investigate on how to resolve.

Maybe @sebmck can chime in and comment if there is a planned ETA when `replaceWithSourceString` (or a replacement) will land again ... :innocent:

**Comment by sebmck** [comment]
@pangratz Shit, sorry. I was meant to add that back in but forgot.

**Comment by pangratz** [comment]
> @pangratz Shit, sorry. I was meant to add that back in but forgot.

Uff, a reply 38 seconds later. :zap: fast sebmck is fast :stuck_out_tongue_winking_eye:

**Comment by pangratz** [comment]
@sebmck Would you accept a PR removing that line?

**Comment by sebmck** [comment]
> Would you accept a PR removing that line?

I was supposed to add it back. Give me a minute, pushing a new version.

**Comment by sebmck** [comment]
Fixed as of 5.7.1, sorry!

**Comment by pangratz** [comment]
> Fixed as of 5.7.1, sorry!

You da man! Thanks for the megafast fix! :heart:

**Comment by blimmer** [comment]
Thanks to both of you for fixing this so quickly.

**Comment by piotrpalek** [comment]
this was fast, nice job thanks :+1:
