### ISSUE TITLE
Is it possible to use it in a jsbin?

### ISSUE THREAD

**Issue by albertjan** [pangratz/ember-cli-htmlbars-inline-precompile#19]
title says it all :smile: 

I was trying to get one of the jsbins from the 0.10 guides to work with the latest release version.

http://guides.emberjs.com/v1.10.0/testing/testing-components/

http://jsbin.com/hikuhi/1/edit?html,js,output

**Comment by pangratz** [comment]
Hey!

Sorry for the late response, but my GitHub notifications did somehow not work.

This addon does nothing more than replacing the tagged template strings with the precompiled version, by using `Handlebars.precompile` from the `ember-template-compiler.js`. This makes sense when the template compiler is not present in the final build.

In your JSBin example you already include the `ember-template-compiler.js`, so this addon is not needed (and also I am not sure if running babel.js addons in the browser is possible). To make the compilation of the templates work, you can simply alias `var hbs = Ember.Handlebars.compile` and change the tagged template string to be the function call:http://jsbin.com/vufubijala/1/edit?html,js,output

``` js
var hbs = Ember.HTMLBars.compile;

// ... later in the component integration test
  
this.render(
  hbs(`{{#my-album title="Cats"}}
            {{my-kitten width="200" height="300"}}
            {{my-kitten width="100" height="100"}}
            {{my-kitten width="50" height="50"}}
          {{/my-album}}`)
);
```

I hope this helps! If not, let me know!

**Comment by albertjan** [comment]
Great thanks! :smile:
