### ISSUE TITLE
Error using precompiler

### ISSUE THREAD

**Issue by mixonic** [pangratz/ember-cli-htmlbars-inline-precompile#2]
Getting:

```
Plugin undefined didn't export a default Transformer instance
TypeError: Plugin undefined didn't export a default Transformer instance
```

Do we need a certain version of Babel?

**Comment by pangratz** [comment]
Replacing a node with a source string has been added in https://github.com/babel/babel/commit/0fc02f2cf09e0b1fe8738646c815b869921863b9 (v5.2.7), but there was a bug so I think at least https://github.com/babel/babel/commit/7e6e5d474641a2bacbfb9602fd371c149b37938c (v5.2.10) is required ...

**Comment by mixonic** [comment]
IT LIVES

![](https://judyblackcloud.files.wordpress.com/2012/04/itlives.jpg)

**Comment by pangratz** [comment]
![obyneqd](https://cloud.githubusercontent.com/assets/341877/7484201/53da44dc-f386-11e4-8898-0af25041ddec.gif)

**Comment by pangratz** [comment]
I added [a section in the README](https://github.com/pangratz/ember-cli-htmlbars-inline-precompile#troubleshooting) if this error occurs.

@mixonic may I ask if that solved the problem you had?

**Comment by mixonic** [comment]
@pangratz yes. I had people delete the directory as you describe, run `npm cache clear` then `npm install`. I believe the `npm cache clear` is not needed.

**Comment by pangratz** [comment]
Thank you sir.
