### ISSUE TITLE
Compile templates with child components?

### ISSUE THREAD

**Issue by quaertym** [pangratz/ember-cli-htmlbars-inline-precompile#27]
It is not clear from README whether compiling this is possible in ember-cli integration tests:
```handlebars
{{my-component user=user}}
```
where `my-component.hbs` uses another component as:
```handlebars
{{! my-component.hbs }}
{{another-component email=user.email}}
```
Can you help?

**Comment by pangratz** [comment]
Merhaba @quaertym,

yep, that works. See [this ember-twiddle](https://ember-twiddle.com/34e0658598a477a10994a4e3dccb567f?fileTreeShown=false&numColumns=2&openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.other-component.hbs) as an example of how this is done.

**Comment by quaertym** [comment]
@pangratz Thanks but how to do this if parent component has no block and `{{yield}}`?

**Comment by pangratz** [comment]
That works too, see [this ember-twiddle](https://ember-twiddle.com/c910e90fe30b48920653681e38532a95?fileTreeShown=false&numColumns=2&openFiles=tests.integration.components.my-component-test.js%2Ctemplates.components.my-component.hbs).

Are you running into a particular issue with `ember-cli-htmlbars-inline-precompile`?

**Comment by quaertym** [comment]
No, actually. I think our test code is problematic.
Tesekkurler. :+1:

**Comment by pangratz** [comment]
Ah, ok. Let me know if you run into any issue, but basically all the templates which work in ember should work in the integration tests too...
